#!/bin/sh
# start the rttov gui application

if [ -z ${RTTOV_GUI_PREFIX} ]
then
	echo "ERROR : the environment variable RTTOV_GUI_PREFIX is not set"
	exit 1
fi
export PATH=${RTTOV_GUI_PREFIX}:$PATH

if [ -z ${RTTOV_GUI_WRK_DIR} ]
then
	if [ ! -r $HOME/.rttov ]
	then
		mkdir  $HOME/.rttov
	fi
export RTTOV_GUI_WRK_DIR=$HOME/.rttov
fi
if [ ! -d ${RTTOV_GUI_WRK_DIR} ]
then
	mkdir -p ${RTTOV_GUI_WRK_DIR}
fi

# update as necessary your PYTHONPATH
export PYTHONPATH=$PYTHONPATH:${RTTOV_GUI_PREFIX}



cd ${RTTOV_GUI_PREFIX}
if [ -z "$1" ]
then
  python rcontroller/controller.py
  exit
fi
case $1 in 
"iasi"|"IASI") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/standard54lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov9pred101L/rtcoef_metop_2_iasi.H5 
;;
"cris"|"CRIS") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/standard54lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov9pred101L/rtcoef_jpss_0_cris.H5 
;;
"pc"|"PC") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cld101lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov9pred101L/rtcoef_metop_2_iasi.H5 -p=${RTTOV_GUI_COEFF_DIR}/pc/pccoef_metop_2_iasi.H5
;;
"cloud"|"clouds") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cld101lev_allgas.H5 -c=${RTTOV_GUI_COEFF_DIR}/cldaer/sccldcoef_jpss_0_viirs.dat -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_jpss_0_viirs.dat
;;
"aer"|"aerosols") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cldaer101lev_allgas.H5  -a=${RTTOV_GUI_COEFF_DIR}/cldaer/scaercoef_jpss_0_viirs.dat -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_jpss_0_viirs.dat
;;
"solar") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cld101lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov9pred54L/rtcoef_eos_2_modis.dat
;;
"ssmi") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cld101lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_dmsp_15_ssmi.dat
;;
"MW"|"mw"|"MO"|"mo") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cld101lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_dmsp_18_ssmis.dat
;;
"landsat") python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cld101lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_landsat_4_tm.dat
;;
'1dvar') python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/standard54lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_metop_2_hirs.dat
;;
'1dvar2') python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/standard54lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_metop_2_mhs.dat
;;
'1dvar3') python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/standard54lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_metop_2_amsua.dat
;;
'1dvar4') python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/standard54lev_allgas.H5 -s=${RTTOV_GUI_COEFF_DIR}/rttov7pred54L/rtcoef_noaa_18_amsua.dat
;;
"PCclouds"|"PCClouds"|"PCCLOUDS")
 coefFile=${RTTOV_GUI_COEFF_DIR}/rttov9pred101L_old/rtcoef_metop_2_iasi.H5
 pcFile=${RTTOV_GUI_COEFF_DIR}/pc//pccoefcld_metop_2_iasi.dat
 pcCloudsFile=${RTTOV_GUI_COEFF_DIR}/cldaer/sccldcoef_metop_2_iasi.H5
 echo "python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cld101lev_allgas.H5 -s=${coefFile} -p=${pcFile} -c=${pcCloudsFile}"
 python rcontroller/controller.py -d -P=${RTTOV_GUI_PROFILE_DIR}/cld101lev_allgas.H5 -s=${coefFile} -p=${pcFile} -c=${pcCloudsFile}
;;

*)  python rcontroller/controller.py
;;
esac
