!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_radiance_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_radiance_def
!use rttov_hdf_radiance_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_radiance_init
public :: rttov_hdf_radiance_rh
public :: rttov_hdf_radiance_wh


contains


subroutine rttov_hdf_radiance_init(x)
type(radiance_type),intent(inout)::x

  nullify(x%CLEAR)
  nullify(x%CLOUDY)
  nullify(x%TOTAL)
  nullify(x%BT)
  nullify(x%BT_CLEAR)
  nullify(x%REFL)
  nullify(x%REFL_CLEAR)
  nullify(x%OVERCAST)
end subroutine

subroutine rttov_hdf_radiance_rh(x,lun,err)
type(radiance_type),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_radiance_init(x)

sname='CLEAR'
call read_array_hdf(lun,sname,err,pr1=x%CLEAR)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='CLOUDY'
call read_array_hdf(lun,sname,err,pr1=x%CLOUDY)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='TOTAL'
call read_array_hdf(lun,sname,err,pr1=x%TOTAL)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='BT'
call read_array_hdf(lun,sname,err,pr1=x%BT)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='BT_CLEAR'
call read_array_hdf(lun,sname,err,pr1=x%BT_CLEAR)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='REFL'
call read_array_hdf(lun,sname,err,pr1=x%REFL)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='REFL_CLEAR'
call read_array_hdf(lun,sname,err,pr1=x%REFL_CLEAR)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='OVERCAST'
call read_array_hdf(lun,sname,err,pr2=x%OVERCAST)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_radiance_wh(x,lun,err,compress)
type(radiance_type),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY
sname='CLEAR'
if(associated(x%CLEAR))then
  call write_array_hdf(lun,sname,&
    & 'Clear sky top of atmosphere radiance (channels)',&
    & err,r1=x%CLEAR , units = 'mw/cm-1/ster/sq.m' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CLOUDY'
if(associated(x%CLOUDY))then
  call write_array_hdf(lun,sname,&
    & 'Cloudy top of atmosphere radiance for 100% fraction for each channel at given cloud top pressure',&
    & err,r1=x%CLOUDY , units = 'mw/cm-1/ster/sq.m' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='TOTAL'
if(associated(x%TOTAL))then
  call write_array_hdf(lun,sname,&
    & 'Clear+cloudy top of atmosphere radiance for given cloud top pressure and fraction',&
    & err,r1=x%TOTAL , units = 'mw/cm-1/ster/sq.m' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='BT'
if(associated(x%BT))then
  call write_array_hdf(lun,sname,&
    & 'Brightness temp equivalent to total radiance',&
    & err,r1=x%BT , units = 'Kelvin' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='BT_CLEAR'
if(associated(x%BT_CLEAR))then
  call write_array_hdf(lun,sname,&
    & 'Brightness temp equivalent to clear radiance',&
    & err,r1=x%BT_CLEAR , units = 'Kelvin' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='REFL'
if(associated(x%REFL))then
  call write_array_hdf(lun,sname,&
    & 'Reflectance calculated from total radiance',&
    & err,r1=x%REFL , units = 'N/A' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='REFL_CLEAR'
if(associated(x%REFL_CLEAR))then
  call write_array_hdf(lun,sname,&
    & 'Reflectance calculated from clear radiance',&
    & err,r1=x%REFL_CLEAR , units = 'N/A' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='OVERCAST'
if(associated(x%OVERCAST))then
  call write_array_hdf(lun,sname,&
    & 'Overcast radiance at given cloud top  (levels,channels)',&
    & err,r2=x%OVERCAST , units = 'mw/cm-1/ster/sq.m' ,compress=compress)
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

err=0_jpim
CATCH
end subroutine

end module
