!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_rttov_fast_coef_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_rttov_fast_coef_def
!use rttov_hdf_rttov_fast_coef_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_rttov_fast_coef_init
public :: rttov_hdf_rttov_fast_coef_rh
public :: rttov_hdf_rttov_fast_coef_wh


contains


subroutine rttov_hdf_rttov_fast_coef_init(x)
type(rttov_fast_coef),intent(inout)::x

  nullify(x%MIXEDGAS)
  nullify(x%WATERVAPOUR)
  nullify(x%OZONE)
  nullify(x%WVCONT)
  nullify(x%CO2)
  nullify(x%N2O)
  nullify(x%CO)
  nullify(x%CH4)
end subroutine

subroutine rttov_hdf_rttov_fast_coef_rh(x,lun,err)
type(rttov_fast_coef),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_rttov_fast_coef_init(x)

sname='MIXEDGAS'
call read_array_hdf(lun,sname,err,pr3=x%MIXEDGAS)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='WATERVAPOUR'
call read_array_hdf(lun,sname,err,pr3=x%WATERVAPOUR)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='OZONE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr3=x%OZONE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='WVCONT'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr3=x%WVCONT)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CO2'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr3=x%CO2)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='N2O'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr3=x%N2O)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CO'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr3=x%CO)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CH4'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr3=x%CH4)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_rttov_fast_coef_wh(x,lun,err,compress)
type(rttov_fast_coef),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY
sname='MIXEDGAS'
if(associated(x%MIXEDGAS))then
  call write_array_hdf(lun,sname,&
    & 'Coefficients for Mixed gases',&
    & err,r3=x%MIXEDGAS , units = 'n/a' ,compress=compress,compdims=(/-1,-1,1/))
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='WATERVAPOUR'
if(associated(x%WATERVAPOUR))then
  call write_array_hdf(lun,sname,&
    & 'Coefficients for Water vapour',&
    & err,r3=x%WATERVAPOUR , units = 'n/a' ,compress=compress,compdims=(/-1,-1,1/))
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='OZONE'
if(associated(x%OZONE))then
  call write_array_hdf(lun,sname,&
    & 'Coefficients for Ozone',&
    & err,r3=x%OZONE , units = 'n/a' ,compress=compress,compdims=(/-1,-1,1/))
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='WVCONT'
if(associated(x%WVCONT))then
  call write_array_hdf(lun,sname,&
    & 'Coefficients for Water vapour continuum',&
    & err,r3=x%WVCONT , units = 'n/a' ,compress=compress,compdims=(/-1,-1,1/))
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CO2'
if(associated(x%CO2))then
  call write_array_hdf(lun,sname,&
    & 'Coefficients for Carbon Dioxide',&
    & err,r3=x%CO2 , units = 'n/a' ,compress=compress,compdims=(/-1,-1,1/))
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='N2O'
if(associated(x%N2O))then
  call write_array_hdf(lun,sname,&
    & 'Coefficients for Nitrous oxide',&
    & err,r3=x%N2O , units = 'n/a' ,compress=compress,compdims=(/-1,-1,1/))
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CO'
if(associated(x%CO))then
  call write_array_hdf(lun,sname,&
    & 'Coefficients for Carbon Monoxide',&
    & err,r3=x%CO , units = 'n/a' ,compress=compress,compdims=(/-1,-1,1/))
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CH4'
if(associated(x%CH4))then
  call write_array_hdf(lun,sname,&
    & 'Coefficients for Methane',&
    & err,r3=x%CH4 , units = 'n/a' ,compress=compress,compdims=(/-1,-1,1/))
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

err=0_jpim
CATCH
end subroutine

end module
