!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_opt_param_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_opt_param_def
!use rttov_hdf_opt_param_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_opt_param_init
public :: rttov_hdf_opt_param_rh
public :: rttov_hdf_opt_param_wh


contains


subroutine rttov_hdf_opt_param_init(x)
type(rttov_opt_param),intent(inout)::x

  nullify(x%ABS)
  nullify(x%SCA)
  nullify(x%BPR)
  nullify(x%PHA)
  nullify(x%PHANGLE)
  x%MINPHADIFF=0._jprb
  nullify(x%COSPHANGLE)
  nullify(x%IPHANGLE)
end subroutine

subroutine rttov_hdf_opt_param_rh(x,lun,err)
type(rttov_opt_param),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_opt_param_init(x)

sname='ABS'
call read_array_hdf(lun,sname,err,pr2=x%ABS)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='SCA'
call read_array_hdf(lun,sname,err,pr2=x%SCA)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='BPR'
call read_array_hdf(lun,sname,err,pr2=x%BPR)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='PHA'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr3=x%PHA)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='PHANGLE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%PHANGLE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif




err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_opt_param_wh(x,lun,err,compress)
type(rttov_opt_param),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY
sname='ABS'
if(associated(x%ABS))then
  call write_array_hdf(lun,sname,&
    & 'Absorption coef',&
    & err,r2=x%ABS , units = 'n/a' ,compress=compress)
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='SCA'
if(associated(x%SCA))then
  call write_array_hdf(lun,sname,&
    & 'Scattering coef',&
    & err,r2=x%SCA , units = 'n/a' ,compress=compress)
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='BPR'
if(associated(x%BPR))then
  call write_array_hdf(lun,sname,&
    & 'Back scattering factor',&
    & err,r2=x%BPR , units = 'n/a' ,compress=compress)
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='PHA'
if(associated(x%PHA))then
  call write_array_hdf(lun,sname,&
    & 'Phase function',&
    & err,r3=x%PHA , units = 'n/a' ,compress=compress)
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='PHANGLE'
if(associated(x%PHANGLE))then
  call write_array_hdf(lun,sname,&
    & 'Angles over which phase fns defined ',&
    & err,r1=x%PHANGLE , units = 'n/a' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif




err=0_jpim
CATCH
end subroutine

end module
