!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_options_rt_mw_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_options_rt_mw_def
!use rttov_hdf_options_rt_mw_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_options_rt_mw_init
public :: rttov_hdf_options_rt_mw_rh
public :: rttov_hdf_options_rt_mw_wh


contains


subroutine rttov_hdf_options_rt_mw_init(x)
type(rttov_opts_rt_mw),intent(inout)::x

  x%FASTEM_VERSION=5_jpim
  x%SUPPLY_FOAM_FRACTION=.FALSE.
  x%CLW_DATA=.FALSE.
  x%DO_LAMBERTIAN=.FALSE.
end subroutine

subroutine rttov_hdf_options_rt_mw_rh(x,lun,err)
type(rttov_opts_rt_mw),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_options_rt_mw_init(x)

sname='FASTEM_VERSION'
call read_array_hdf(lun,sname,err,i0=x%FASTEM_VERSION)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='SUPPLY_FOAM_FRACTION'
call read_array_hdf(lun,sname,err,l0=x%SUPPLY_FOAM_FRACTION)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='CLW_DATA'
call read_array_hdf(lun,sname,err,l0=x%CLW_DATA)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='DO_LAMBERTIAN'
call read_array_hdf(lun,sname,err,l0=x%DO_LAMBERTIAN)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_options_rt_mw_wh(x,lun,err,compress)
type(rttov_opts_rt_mw),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY
sname='FASTEM_VERSION'
call write_array_hdf(lun,sname,&
  & 'Fastem version; Valid range: 1-5. Otherwise version taken from coef file',&
  & err,i0=x%FASTEM_VERSION  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='SUPPLY_FOAM_FRACTION'
call write_array_hdf(lun,sname,&
  & 'Use ocean foam fraction value in input profile in FASTEM',&
  & err,l0=x%SUPPLY_FOAM_FRACTION  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='CLW_DATA'
call write_array_hdf(lun,sname,&
  & 'Profile contains Cloud Liquid Water profile',&
  & err,l0=x%CLW_DATA  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='DO_LAMBERTIAN'
call write_array_hdf(lun,sname,&
  & 'Activate treatment of surface as Lambertian instead of specular reflector for downwelling emitted radiation',&
  & err,l0=x%DO_LAMBERTIAN  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

err=0_jpim
CATCH
end subroutine

end module
