!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_options_config_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_options_config_def
!use rttov_hdf_options_config_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_options_config_init
public :: rttov_hdf_options_config_rh
public :: rttov_hdf_options_config_wh


contains


subroutine rttov_hdf_options_config_init(x)
type(rttov_opts_config),intent(inout)::x

  x%APPLY_REG_LIMITS=.FALSE.
  x%VERBOSE=.TRUE.
  x%DO_CHECKINPUT=.TRUE.
end subroutine

subroutine rttov_hdf_options_config_rh(x,lun,err)
type(rttov_opts_config),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_options_config_init(x)

sname='APPLY_REG_LIMITS'
call read_array_hdf(lun,sname,err,l0=x%APPLY_REG_LIMITS)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='VERBOSE'
call read_array_hdf(lun,sname,err,l0=x%VERBOSE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='DO_CHECKINPUT'
call read_array_hdf(lun,sname,err,l0=x%DO_CHECKINPUT)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_options_config_wh(x,lun,err,compress)
type(rttov_opts_config),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY
sname='APPLY_REG_LIMITS'
call write_array_hdf(lun,sname,&
  & 'Input profiles outside the limits specified in the coefficient files are reset to the min/max',&
  & err,l0=x%APPLY_REG_LIMITS  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='VERBOSE'
call write_array_hdf(lun,sname,&
  & 'verbose',&
  & err,l0=x%VERBOSE  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='DO_CHECKINPUT'
call write_array_hdf(lun,sname,&
  & 'Checks whether input profiles are within both absolute and regression limits',&
  & err,l0=x%DO_CHECKINPUT  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

err=0_jpim
CATCH
end subroutine

end module
