!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_options_pc_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_options_pc_def
!use rttov_hdf_options_pc_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_options_pc_init
public :: rttov_hdf_options_pc_rh
public :: rttov_hdf_options_pc_wh


contains


subroutine rttov_hdf_options_pc_init(x)
type(rttov_opts_pc),intent(inout)::x

  x%IPCREG=-1_jpim
  x%IPCBND=-1_jpim
  x%ADDPC=.FALSE.
  x%ADDRADREC=.FALSE.
end subroutine

subroutine rttov_hdf_options_pc_rh(x,lun,err)
type(rttov_opts_pc),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_options_pc_init(x)

sname='IPCREG'
call read_array_hdf(lun,sname,err,i0=x%IPCREG)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='IPCBND'
call read_array_hdf(lun,sname,err,i0=x%IPCBND)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='ADDPC'
call read_array_hdf(lun,sname,err,l0=x%ADDPC)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='ADDRADREC'
call read_array_hdf(lun,sname,err,l0=x%ADDRADREC)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_options_pc_wh(x,lun,err,compress)
type(rttov_opts_pc),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY
sname='IPCREG'
call write_array_hdf(lun,sname,&
  & 'The index of the required set of PC predictors 1-4 for IASI, 1-3 for AIRS',&
  & err,i0=x%IPCREG  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='IPCBND'
call write_array_hdf(lun,sname,&
  & 'The index of the required spectral band for PC-RTTOV 1-3 for IASI clear-sky, 1 otherwise',&
  & err,i0=x%IPCBND  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='ADDPC'
call write_array_hdf(lun,sname,&
  & 'Carry out Principal Components calculations',&
  & err,l0=x%ADDPC  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='ADDRADREC'
call write_array_hdf(lun,sname,&
  & 'If addpc is true, the PC calculations will return reconstructed radiances',&
  & err,l0=x%ADDRADREC  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

err=0_jpim
CATCH
end subroutine

end module
