!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_options_rt_ir_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_options_rt_ir_def
!use rttov_hdf_options_rt_ir_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_options_rt_ir_init
public :: rttov_hdf_options_rt_ir_rh
public :: rttov_hdf_options_rt_ir_wh


contains


subroutine rttov_hdf_options_rt_ir_init(x)
type(rttov_opts_rt_ir),intent(inout)::x

  x%CLDSTR_THRESHOLD=-1.0_jprb
  x%CLDSTR_SIMPLE=.FALSE.
  x%ADDSOLAR=.FALSE.
  x%ADDAEROSL=.FALSE.
  x%ADDCLOUDS=.FALSE.
  x%USER_AER_OPT_PARAM=.FALSE.
  x%USER_CLD_OPT_PARAM=.FALSE.
  x%OZONE_DATA=.FALSE.
  x%CO2_DATA=.FALSE.
  x%N2O_DATA=.FALSE.
  x%CO_DATA=.FALSE.
  x%CH4_DATA=.FALSE.
  x%DO_NLTE_CORRECTION=.FALSE.
  x%DO_LAMBERTIAN=.FALSE.
end subroutine

subroutine rttov_hdf_options_rt_ir_rh(x,lun,err)
type(rttov_opts_rt_ir),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_options_rt_ir_init(x)


sname='CLDSTR_THRESHOLD'
call read_array_hdf(lun,sname,err,r0=x%CLDSTR_THRESHOLD)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='CLDSTR_SIMPLE'
call read_array_hdf(lun,sname,err,l0=x%CLDSTR_SIMPLE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='ADDSOLAR'
call read_array_hdf(lun,sname,err,l0=x%ADDSOLAR)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='ADDAEROSL'
call read_array_hdf(lun,sname,err,l0=x%ADDAEROSL)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='ADDCLOUDS'
call read_array_hdf(lun,sname,err,l0=x%ADDCLOUDS)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='USER_AER_OPT_PARAM'
call read_array_hdf(lun,sname,err,l0=x%USER_AER_OPT_PARAM)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='USER_CLD_OPT_PARAM'
call read_array_hdf(lun,sname,err,l0=x%USER_CLD_OPT_PARAM)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='OZONE_DATA'
call read_array_hdf(lun,sname,err,l0=x%OZONE_DATA)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='CO2_DATA'
call read_array_hdf(lun,sname,err,l0=x%CO2_DATA)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='N2O_DATA'
call read_array_hdf(lun,sname,err,l0=x%N2O_DATA)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='CO_DATA'
call read_array_hdf(lun,sname,err,l0=x%CO_DATA)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='CH4_DATA'
call read_array_hdf(lun,sname,err,l0=x%CH4_DATA)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='DO_NLTE_CORRECTION'
call read_array_hdf(lun,sname,err,l0=x%DO_NLTE_CORRECTION)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='DO_LAMBERTIAN'
call read_array_hdf(lun,sname,err,l0=x%DO_LAMBERTIAN)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_options_rt_ir_wh(x,lun,err,compress)
type(rttov_opts_rt_ir),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY

sname='CLDSTR_THRESHOLD'
call write_array_hdf(lun,sname,&
  & 'Cloud threshold, recommended to set this negative for TL/AD/K',&
  & err,r0=x%CLDSTR_THRESHOLD  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='CLDSTR_SIMPLE'
call write_array_hdf(lun,sname,&
  & 'Simplified cloud stream option (one clear and one cloudy stream) appropriate only for high-peaking channels',&
  & err,l0=x%CLDSTR_SIMPLE  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='ADDSOLAR'
call write_array_hdf(lun,sname,&
  & 'Enable solar calculations',&
  & err,l0=x%ADDSOLAR  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='ADDAEROSL'
call write_array_hdf(lun,sname,&
  & 'Account for scattering due to aerosols',&
  & err,l0=x%ADDAEROSL  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='ADDCLOUDS'
call write_array_hdf(lun,sname,&
  & 'account for scattering due to clouds',&
  & err,l0=x%ADDCLOUDS  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='USER_AER_OPT_PARAM'
call write_array_hdf(lun,sname,&
  & 'User input for aerosols optical parameters',&
  & err,l0=x%USER_AER_OPT_PARAM  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='USER_CLD_OPT_PARAM'
call write_array_hdf(lun,sname,&
  & 'User input for cloud optical parameters',&
  & err,l0=x%USER_CLD_OPT_PARAM  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='OZONE_DATA'
call write_array_hdf(lun,sname,&
  & 'Profile contains Ozone data',&
  & err,l0=x%OZONE_DATA  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='CO2_DATA'
call write_array_hdf(lun,sname,&
  & 'Profile contains CO2 data',&
  & err,l0=x%CO2_DATA  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='N2O_DATA'
call write_array_hdf(lun,sname,&
  & 'Profile contains N2O data',&
  & err,l0=x%N2O_DATA  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='CO_DATA'
call write_array_hdf(lun,sname,&
  & 'Profile contains CO data',&
  & err,l0=x%CO_DATA  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='CH4_DATA'
call write_array_hdf(lun,sname,&
  & 'Profile contains CH4 data',&
  & err,l0=x%CH4_DATA  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='DO_NLTE_CORRECTION'
call write_array_hdf(lun,sname,&
  & 'Enable Non Local Thermal Equilibrium (NLTE) calculations',&
  & err,l0=x%DO_NLTE_CORRECTION  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='DO_LAMBERTIAN'
call write_array_hdf(lun,sname,&
  & 'Activate treatment of surface as Lambertian instead of specular reflector for downwelling emitted radiation',&
  & err,l0=x%DO_LAMBERTIAN  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

err=0_jpim
CATCH
end subroutine

end module
