!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_profile_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_profile_def
!use rttov_hdf_profile_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_profile_init
public :: rttov_hdf_profile_rh
public :: rttov_hdf_profile_wh


contains


subroutine rttov_hdf_profile_init(x)
type(profile_type),intent(inout)::x

  x%ID=''
  x%DATE=0_jpim
  x%TIME=0_jpim
  x%NLEVELS=0_jpim
  x%NLAYERS=0_jpim
  x%GAS_UNITS=0_jpim
  nullify(x%P)
  nullify(x%T)
  nullify(x%Q)
  nullify(x%O3)
  nullify(x%CO2)
  nullify(x%N2O)
  nullify(x%CO)
  nullify(x%CH4)
  nullify(x%CLW)
  nullify(x%AEROSOLS)
  nullify(x%CLOUD)
  nullify(x%CFRAC)
  nullify(x%ICEDE)
  x%IDG=-1_jpim
  x%ISH=-1_jpim
  x%ZENANGLE=0._jprb
  x%AZANGLE=0._jprb
  x%SUNZENANGLE=0._jprb
  x%SUNAZANGLE=0._jprb
  x%ELEVATION=0._jprb
  x%LATITUDE=0._jprb
  x%LONGITUDE=0._jprb
  x%SNOW_FRAC=0._jprb
  x%SOIL_MOISTURE=0._jprb
  x%BE=0._jprb
  x%COSBK=0._jprb
  x%CTP=500._jprb
  x%CFRACTION=0._jprb
end subroutine

subroutine rttov_hdf_profile_rh(x,lun,err)
type(profile_type),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_profile_init(x)

sname='ID'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,c0=x%ID)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='DATE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,i1=x%DATE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='TIME'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,i1=x%TIME)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='NLEVELS'
call read_array_hdf(lun,sname,err,i0=x%NLEVELS)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='NLAYERS'
call read_array_hdf(lun,sname,err,i0=x%NLAYERS)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='GAS_UNITS'
call read_array_hdf(lun,sname,err,i0=x%GAS_UNITS)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='P'
call read_array_hdf(lun,sname,err,pr1=x%P)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='T'
call read_array_hdf(lun,sname,err,pr1=x%T)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='Q'
call read_array_hdf(lun,sname,err,pr1=x%Q)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='O3'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%O3)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CO2'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%CO2)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='N2O'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%N2O)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CO'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%CO)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CH4'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%CH4)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CLW'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%CLW)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='AEROSOLS'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr2=x%AEROSOLS)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CLOUD'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr2=x%CLOUD)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CFRAC'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%CFRAC)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='ICEDE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,pr1=x%ICEDE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='IDG'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,i0=x%IDG)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='ISH'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,i0=x%ISH)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif



sname='ZENANGLE'
call read_array_hdf(lun,sname,err,r0=x%ZENANGLE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='AZANGLE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%AZANGLE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='SUNZENANGLE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%SUNZENANGLE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='SUNAZANGLE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%SUNAZANGLE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='ELEVATION'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%ELEVATION)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='LATITUDE'
call read_array_hdf(lun,sname,err,r0=x%LATITUDE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='LONGITUDE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%LONGITUDE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='SNOW_FRAC'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%SNOW_FRAC)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='SOIL_MOISTURE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%SOIL_MOISTURE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='BE'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%BE)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='COSBK'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%COSBK)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CTP'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%CTP)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

sname='CFRACTION'
call h5lexists_f( lun, sname, lext, err )
if( lext ) then
call read_array_hdf(lun,sname,err,r0=x%CFRACTION)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))
endif

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_profile_wh(x,lun,err,compress)
type(profile_type),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY
sname='ID'
call write_array_hdf(lun,sname,&
  & 'User may give text ID to each profile',&
  & err,c0=x%ID  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='DATE'
call write_array_hdf(lun,sname,&
  & 'Year Month Day',&
  & err,i1=x%DATE  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='TIME'
call write_array_hdf(lun,sname,&
  & 'Hour Minute Second',&
  & err,i1=x%TIME  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='NLEVELS'
call write_array_hdf(lun,sname,&
  & 'Number of atmospheric levels',&
  & err,i0=x%NLEVELS  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='NLAYERS'
call write_array_hdf(lun,sname,&
  & 'Number of atmospheric layers',&
  & err,i0=x%NLAYERS  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='GAS_UNITS'
call write_array_hdf(lun,sname,&
  & 'Units for gas profiles',&
  & err,i0=x%GAS_UNITS  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='P'
if(associated(x%P))then
  call write_array_hdf(lun,sname,&
    & 'Pressure',&
    & err,r1=x%P , units = 'hPa' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='T'
if(associated(x%T))then
  call write_array_hdf(lun,sname,&
    & 'Temperature',&
    & err,r1=x%T , units = 'K' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='Q'
if(associated(x%Q))then
  call write_array_hdf(lun,sname,&
    & 'Water vapour',&
    & err,r1=x%Q , units = 'ppmv or kg/kg' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='O3'
if(associated(x%O3))then
  call write_array_hdf(lun,sname,&
    & 'Ozone',&
    & err,r1=x%O3 , units = 'ppmv or kg/kg' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CO2'
if(associated(x%CO2))then
  call write_array_hdf(lun,sname,&
    & 'Carbon dioxide',&
    & err,r1=x%CO2 , units = 'ppmv or kg/kg' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='N2O'
if(associated(x%N2O))then
  call write_array_hdf(lun,sname,&
    & 'N2O',&
    & err,r1=x%N2O , units = 'ppmv or kg/kg' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CO'
if(associated(x%CO))then
  call write_array_hdf(lun,sname,&
    & 'CO',&
    & err,r1=x%CO , units = 'ppmv or kg/kg' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CH4'
if(associated(x%CH4))then
  call write_array_hdf(lun,sname,&
    & 'CH4',&
    & err,r1=x%CH4 , units = 'ppmv or kg/kg' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CLW'
if(associated(x%CLW))then
  call write_array_hdf(lun,sname,&
    & 'Cloud liquid water - MW only',&
    & err,r1=x%CLW , units = 'kg/kg' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='AEROSOLS'
if(associated(x%AEROSOLS))then
  call write_array_hdf(lun,sname,&
    & 'Aerosols - IR only',&
    & err,r2=x%AEROSOLS , units = 'number density (cm^-3)' ,compress=compress)
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CLOUD'
if(associated(x%CLOUD))then
  call write_array_hdf(lun,sname,&
    & 'Cloud water/ice - IR only',&
    & err,r2=x%CLOUD , units = 'g/m^3' ,compress=compress)
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='CFRAC'
if(associated(x%CFRAC))then
  call write_array_hdf(lun,sname,&
    & 'Cloud fractional cover (0-1) - IR only',&
    & err,r1=x%CFRAC , units = '0:1' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='ICEDE'
if(associated(x%ICEDE))then
  call write_array_hdf(lun,sname,&
    & 'Ice crystals diameter - IR only',&
    & err,r1=x%ICEDE , units = 'microns' )
  THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))
endif

sname='IDG'
call write_array_hdf(lun,sname,&
  & 'Scheme for IWC to eff diameter, Dg 1=Ou and Liou; 2=Wyser et al; 3=Boudala et al; 4=McFarquhar et al',&
  & err,i0=x%IDG  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='ISH'
call write_array_hdf(lun,sname,&
  & 'Choose the shape of ice crystals, 1=Hexagonal ice crystals; 2=Ice aggregates; 3=Baran 2013 scheme; 4=Baran 2014 scheme',&
  & err,i0=x%ISH  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))



sname='ZENANGLE'
call write_array_hdf(lun,sname,&
  & 'Satellite zenith angle',&
  & err,r0=x%ZENANGLE , units = 'degree' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='AZANGLE'
call write_array_hdf(lun,sname,&
  & 'Satellite azimuth angle',&
  & err,r0=x%AZANGLE , units = 'degree (0-360 deg; east=90)' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='SUNZENANGLE'
call write_array_hdf(lun,sname,&
  & 'Sun zenith angle',&
  & err,r0=x%SUNZENANGLE , units = 'degree' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='SUNAZANGLE'
call write_array_hdf(lun,sname,&
  & 'Sun azimuth angle',&
  & err,r0=x%SUNAZANGLE , units = 'degree (0-360 deg; east=90)' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='ELEVATION'
call write_array_hdf(lun,sname,&
  & 'Surface elevaton',&
  & err,r0=x%ELEVATION , units = 'km' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='LATITUDE'
call write_array_hdf(lun,sname,&
  & 'Latitude',&
  & err,r0=x%LATITUDE , units = 'degree' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='LONGITUDE'
call write_array_hdf(lun,sname,&
  & 'Longitude',&
  & err,r0=x%LONGITUDE , units = 'degree (0-360)' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='SNOW_FRAC'
call write_array_hdf(lun,sname,&
  & 'Surface snow coverage fraction (0-1). Used only by IR emissivity atlas ',&
  & err,r0=x%SNOW_FRAC , units = '0:1' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='SOIL_MOISTURE'
call write_array_hdf(lun,sname,&
  & 'soil moisture',&
  & err,r0=x%SOIL_MOISTURE , units = 'm^3/m^3' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='BE'
call write_array_hdf(lun,sname,&
  & 'Earth magnetic field strength',&
  & err,r0=x%BE , units = 'Gauss' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='COSBK'
call write_array_hdf(lun,sname,&
  & 'Cosine of the angle between the Earth magnetic field and wave propagation direction',&
  & err,r0=x%COSBK  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='CTP'
call write_array_hdf(lun,sname,&
  & 'Black body cloud top pressure',&
  & err,r0=x%CTP , units = 'hPa' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='CFRACTION'
call write_array_hdf(lun,sname,&
  & 'Black body cloud fraction (0-1), 1 for 100% cloud cover',&
  & err,r0=x%CFRACTION , units = '0:1' )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

err=0_jpim
CATCH
end subroutine

end module
