!
! Automatically generated by ./mod_rw_for_rttov_types.pl
! Do not edit
!
module rttov_hdf_options_rt_all_io
#include "throw.h"
use parkind1
!use rttov_print_mod
use rttov_hdf_mod
!use rttov_hdf_options_rt_all_def
!use rttov_hdf_options_rt_all_mem
use rttov_types

use hdf5
implicit none
#include "rttov_errorreport.interface"
private
public :: rttov_hdf_options_rt_all_init
public :: rttov_hdf_options_rt_all_rh
public :: rttov_hdf_options_rt_all_wh


contains


subroutine rttov_hdf_options_rt_all_init(x)
type(rttov_opts_rt_all),intent(inout)::x

  x%SWITCHRAD=.FALSE.
  x%ADDREFRAC=.FALSE.
  x%USE_Q2M=.TRUE.
  x%DO_LAMBERTIAN=.FALSE.
end subroutine

subroutine rttov_hdf_options_rt_all_rh(x,lun,err)
type(rttov_opts_rt_all),intent(out)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
character(len=lensh)::sname
logical :: lext
TRY

call rttov_hdf_options_rt_all_init(x)

sname='SWITCHRAD'
call read_array_hdf(lun,sname,err,l0=x%SWITCHRAD)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='ADDREFRAC'
call read_array_hdf(lun,sname,err,l0=x%ADDREFRAC)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='USE_Q2M'
call read_array_hdf(lun,sname,err,l0=x%USE_Q2M)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

sname='DO_LAMBERTIAN'
call read_array_hdf(lun,sname,err,l0=x%DO_LAMBERTIAN)
THROWM(err.ne.0,"CANNOT READ "//trim(sname))

err=0_jpim
CATCH
end subroutine

subroutine rttov_hdf_options_rt_all_wh(x,lun,err,compress)
type(rttov_opts_rt_all),intent(in)::x
integer(hid_t),intent(in)::lun
integer(kind=jpim),intent(out)::err
logical,intent(in),optional::compress
character(len=lensh)::sname

TRY
sname='SWITCHRAD'
call write_array_hdf(lun,sname,&
  & 'Determines input perturbation for AD/K: if true, radiance_k%bt is used, otherwise radiance_k%total',&
  & err,l0=x%SWITCHRAD  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='ADDREFRAC'
call write_array_hdf(lun,sname,&
  & 'RTTOV calculations account for atmospheric refraction',&
  & err,l0=x%ADDREFRAC  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='USE_Q2M'
call write_array_hdf(lun,sname,&
  & 'Activate use of surface humidity',&
  & err,l0=x%USE_Q2M  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

sname='DO_LAMBERTIAN'
call write_array_hdf(lun,sname,&
  & 'Activate treatment of surface as Lambertian instead of specular reflector for downwelling emitted radiation',&
  & err,l0=x%DO_LAMBERTIAN  )
THROWM(err.ne.0,"CANNOT WRITE "//trim(sname))

err=0_jpim
CATCH
end subroutine

end module
